sudo: false
dist: trusty
language: node_js
branches:
  only:
    - master
jobs:
  fast_finish: true
  allow_failures:
    - env: WEBPACK_VERSION=canary
  include:
    - &test-latest
      stage: Webpack latest
      node_js: 9
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run travis:test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
before_install:
  - nvm --version
  - node --version
  - npm --version
before_script:
  - |-
    if [ "$WEBPACK_VERSION" ]; then
      npm i --no-save webpack@$WEBPACK_VERSION
    fi
script:
  - 'npm run travis:test'

